name: ie-bank-infra

on:
  push:
    branches:
      - '*'
      - '!main'
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  RESOURCE_GROUP_DEV: aguadamillas_students_1
  RESOURCE_GROUP_UAT: aguadamillas_students_1
  SUBSCRIPTION_ID_DEV: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
  SUBSCRIPTION_ID_UAT: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
  USER_ALIAS: sarwari

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Run Bicep linter for key-vault
        run: az bicep build --file ./key-vault.bicep

      - name: Run Bicep linter for main
        run: az bicep build --file ./main.bicep

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
    env:
      ENV: dev
      DBHOST: sarwari-dbsrv-dev.postgres.database.azure.com
      DBNAME: sarwari-db-dev
      DBUSER: 'iebankdbadmin'
      DBPASS: 'IE.Bank.DB.Admin.Pa$$'
      FLASK_APP: app.py
      FLASK_DEBUG: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Log into Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Key Vault
        uses: azure/arm-deploy@v1.0.9
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID_DEV }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_DEV }}
          template: ./key-vault.bicep
          parameters: ./kv-parameters.json
          deploymentName: "${{ env.USER_ALIAS }}-kv"
          failOnStdErr: false

      - name: Deploy Bicep file
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID_DEV }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_DEV }}
          template: ./main.bicep
          parameters: ./parameters/dev.parameters.json appServiceAPIEnvVarENV=${{ env.ENV }} appServiceAPIEnvVarDBHOST=${{ env.DBHOST }} appServiceAPIEnvVarDBNAME=${{ env.DBNAME }} appServiceAPIEnvVarDBPASS=${{ env.DBPASS }} appServiceAPIDBHostDBUSER=${{ env.DBUSER }} appServiceAPIDBHostFLASK_APP=${{ env.FLASK_APP }} appServiceAPIDBHostFLASK_DEBUG=${{ env.FLASK_DEBUG }}
          deploymentName: ${{ env.USER_ALIAS }}

  deploy-uat:
    runs-on: ubuntu-latest
    needs: [build, deploy-dev]
    environment:
      name: 'User Acceptance Testing'
    env:
      ENV: uat
      DBHOST: sarwari-dbsrv-uat.postgres.database.azure.com
      DBNAME: sarwari-db-uat
      DBUSER: 'iebankdbadmin'
      DBPASS: 'IE.Bank.DB.Admin.Pa$$'
      FLASK_APP: app.py
      FLASK_DEBUG: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Log into Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep file
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID_UAT }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_UAT }}
          template: ./main.bicep
          parameters: ./parameters/uat.json appServiceAPIEnvVarENV=${{ env.ENV }} appServiceAPIEnvVarDBHOST=${{ env.DBHOST }} appServiceAPIEnvVarDBNAME=${{ env.DBNAME }} appServiceAPIEnvVarDBPASS=${{ env.DBPASS }} appServiceAPIDBHostDBUSER=${{ env.DBUSER }} appServiceAPIDBHostFLASK_APP=${{ env.FLASK_APP }} appServiceAPIDBHostFLASK_DEBUG=${{ env.FLASK_DEBUG }}
          deploymentName: ${{ env.USER_ALIAS }}
